name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Working on AWS CLI 2
        run: |
          aws --version
      - run: echo "We Run Latest Ubuntu Operating System from Docker Registry"
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Checking working directory
      - run: |
          pwd
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - uses: NubeEra-Samples/git2s3@master
        with:
          command: cp
          source: ./local_file.txt
          destination: s3://bkt28novmujahed/input/local_file.txt
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
